from typing import Dict

from src.Equipment import Equipment
from src.ExerciseType import ExerciseType
from src.MovementType import MovementType
from src.MovementDirection import MovementDirection
from src.MuscleContractions import MuscleContractions
from src.MuscleGroup import MuscleGroup
from src.MuscleLength import MuscleLength
from src.CategoryGenerator import CategoryGenerator

category_generator_config = [
    Equipment,
    ExerciseType,
    MovementType,
    MovementDirection,
    MuscleGroup,
    MuscleLength,
    MuscleContractions,
]

generator = CategoryGenerator(category_generator_config)

Exercises: Dict[str, Dict[str, str]] = {
    'Bench Press (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.DELTOID],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Squat (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.QUADRICEPS, MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.CALVES],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Lat Pulldown (Cable)': generator.generate(
        Equipment.CABLE,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Leg Extension (Machine)': generator.generate(
        Equipment.MACHINE,
        ExerciseType.COMPOUND,
        MovementType.LEGS,
        MovementDirection.VERTICAL,
        [MuscleGroup.QUADRICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),

    'Triceps Extension': generator.generate(
        Equipment.CABLE,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.TRICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Bicep Curl (Dumbbell)': generator.generate(
        Equipment.DUMBELL,
        ExerciseType.ISOLATION,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Bench Press - Close Grip (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.TRICEPS, MuscleGroup.CHEST, MuscleGroup.DELTOID],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Overhead Press (Dumbbell)': generator.generate(
        Equipment.DUMBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.DELTOID, MuscleGroup.TRICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Lat Pulldown - Underhand (Band)': generator.generate(
        Equipment.BANDS,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Front Squat (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.QUADRICEPS, MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.CALVES],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Incline Bench Press (Dumbbell)': generator.generate(
        Equipment.DUMBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.INCLINE,
        [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.DELTOID],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Cable Crossover': generator.generate(
        Equipment.CABLE,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.CHEST],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Deadlift (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.QUADRICEPS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.BACK, MuscleGroup.CALVES],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Chest Fly (Band)': generator.generate(
        Equipment.BANDS,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.CHEST],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Lat Pulldown (Single Arm)': generator.generate(
        Equipment.CABLE,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Bench Dip': generator.generate(
        Equipment.BODYWEIGHT,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.TRICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Front Raise (Plate)': generator.generate(
        Equipment.PLATE,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.DELTOID],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Bicep Curl (Cable)': generator.generate(
        Equipment.CABLE,
        ExerciseType.ISOLATION,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Front Raise (Cable)': generator.generate(
        Equipment.CABLE,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.DELTOID],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Pendlay Row (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Plank': generator.generate(
        Equipment.BODYWEIGHT,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.CORE],
        MuscleLength.NORMAL,
        MuscleContractions.ISOMETRIC,
    ),
    'Romanian Deadlift (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Inverted Row (Bodyweight)': generator.generate(
        Equipment.BODYWEIGHT,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Incline Row (Dumbbell)': generator.generate(
        Equipment.DUMBELL,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.INCLINE,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Kneeling Pulldown (Band)': generator.generate(
        Equipment.BANDS,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Incline Curl (Dumbbell)': generator.generate(
        Equipment.DUMBELL,
        ExerciseType.ISOLATION,
        MovementType.PULL,
        MovementDirection.INCLINE,
        [MuscleGroup.BICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Seated Leg Press (Machine)': generator.generate(
        Equipment.MACHINE,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.QUADRICEPS, MuscleGroup.GLUTES],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Incline Bench Press (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.INCLINE,
        [MuscleGroup.CHEST, MuscleGroup.DELTOID, MuscleGroup.TRICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Lateral Raise (Dumbbell)': generator.generate(
        Equipment.DUMBELL,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.DELTOID],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Side Plank': generator.generate(
        Equipment.BODYWEIGHT,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.CORE],
        MuscleLength.NORMAL,
        MuscleContractions.ISOMETRIC,
    ),
    'Triceps Extension (Cable)': generator.generate(
        Equipment.CABLE,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.TRICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Seated Row (Cable)': generator.generate(
        Equipment.CABLE,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Pull Up': generator.generate(
        Equipment.PULL_UP_BAR,
        ExerciseType.COMPOUND,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BACK, MuscleGroup.BICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Push Up': generator.generate(
        Equipment.BODYWEIGHT,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.CHEST, MuscleGroup.DELTOID, MuscleGroup.TRICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Floor Press (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.CHEST, MuscleGroup.DELTOID, MuscleGroup.TRICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
    'Overhead Press (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.COMPOUND,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.DELTOID, MuscleGroup.TRICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'Bicep Curl (Barbell)': generator.generate(
        Equipment.BARBELL,
        ExerciseType.ISOLATION,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BICEPS],
        MuscleLength.NORMAL,
        MuscleContractions.CONCENTRIC,
    ),
    'TricepsTRX': generator.generate(
        Equipment.BODYWEIGHT,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.TRICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.ECCENTRIC,
    ),
    'Biceps TRX': generator.generate(
        Equipment.BODYWEIGHT,
        ExerciseType.ISOLATION,
        MovementType.PULL,
        MovementDirection.VERTICAL,
        [MuscleGroup.BICEPS],
        MuscleLength.SHORT_LENGTH,
        MuscleContractions.CONCENTRIC,
    ),
    'Triceps Extension (Dumbbell)': generator.generate(
        Equipment.DUMBELL,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.VERTICAL,
        [MuscleGroup.TRICEPS],
        MuscleLength.LONG_LENGTH,
        MuscleContractions.ECCENTRIC,
    ),
    'Ab Wheel': generator.generate(
        Equipment.BODYWEIGHT,
        ExerciseType.ISOLATION,
        MovementType.PUSH,
        MovementDirection.HORIZONTAL,
        [MuscleGroup.CORE],
        MuscleLength.NORMAL,
        MuscleContractions.ECCENTRIC,
    ),
}
